### ISSUE TITLE
Performance issue with oe_media_media_access

### ISSUE THREAD

**Issue by bpironet** [openeuropa/oe_media#159]
We have a website that displays 5 nodes in a view named "Latest 5 publications".
Each node has 2 fields of type media reference of type mulitple with unlimited value. 
Meaning that we have for each node 1 media on the first field and 24 media on the second field (24 languages...) so a total of 25 media per node and a total of 125 medias linked to the view to be displayed. 
We saw that the function oe_media_media_access() is called a lot of times during the page generation when the cache is empty and the page takes 30-60s to render. Using blackfire.io we saw that 83% of the time needed to generate the page is took by this function. 
Could it be possible to cache some calculation in this function or to have a flag to disable this function so that we do not have the performance issue anymore ?

**Comment by upchuk** [comment]
Hey @bpironet 

Just for your information, the function is responsible for checking access to the media based on the nodes that USE the media. Meaning that if no node is accessible to the user, the access is denied the document media. However, this is cached so it's not performant only once.

However, if this logic is not needed on your site, I understand. Was a very old assumption we made and we deprectated. As you can see above the function, we will remove that function in version 2.0. Meanwhile, you can simply use code to remove it if you don't want that logic:

```
function your_module_name_module_implements_alter(&$implementations, $hook) {
  if ($hook === 'media_access' && array_key_exists('oe_media', $implementations)) {
    unset($implementations['oe_media']);
  }
}
```

**Comment by bpironet** [comment]
Hi @upchuk , 

thank you for the tip. I will use that for my specific case.
