### ISSUE TITLE
Drupal 9 support

### ISSUE THREAD

**Issue by didierdemaeyer** [openeuropa/oe_media#160]
### Description

Add support for Drupal 9.

### Additional information

Upgrade Status report:
[single-export-oe_media-2021-03-19T14_19_54+0100.txt](https://github.com/openeuropa/oe_media/files/6171417/single-export-oe_media-2021-03-19T14_19_54%2B0100.txt)

**Comment by brummbar** [comment]
Resolved by #163 .
