### ISSUE TITLE
Code in hook_media_presave() is executed for all media types.

### ISSUE THREAD

**Issue by heartdriven** [openeuropa/oe_media#209]
PR #206 introduces a bug where for each media type that is saved that isn't managed by oe_media, the code in hook_media_presave() is executed and breaks.  
We have multiple media types that cannot be saved anymore because of this code.  Therefore I have created a PR that simply checks if the oe_media_image field exists, before the values for the alt thumbnails are being read.

**Comment by pindhub** [comment]
Hello,
Experiencing the same issue. PR #210 solves it for me.

**Comment by brummbar** [comment]
@heartdriven , @pindhub thanks a lot for reporting the bug!

**Comment by brummbar** [comment]
Due to internal policy our tests cannot run from forks, I created a new pull request #213 , took your commit @heartdriven , added tests and made it more generic so that it works for all bundles using the image source.

**Comment by heartdriven** [comment]
Perfect, I'm happy to see it get merged eitherhow.
Thanks!

**Comment by brummbar** [comment]
Thanks again a lot for the contribution, I'll see to get it released asap. Happy holidays!

**Comment by ansergeyg** [comment]
Do you, guys, have this error message when saving media or node with media field ?

`Message 	InvalidArgumentException: Field oe_media_image is unknown. in Drupal\Core\Entity\ContentEntityBase->getTranslatedField() (line 587 of web/core/lib/Drupal/Core/Entity/ContentEntityBase.php).`

**Comment by brummbar** [comment]
Released https://github.com/openeuropa/oe_media/releases/tag/1.21.1 with the fix.
