### ISSUE TITLE
Remove CKEditor4 dependency from oe_media_embed module

### ISSUE THREAD

**Issue by vengador** [openeuropa/oe_media#233]
As I commented in https://github.com/openeuropa/oe_oembed/issues/50, due to CKEditor 5 support added to 0.9.0 version of oe_oembed module, there is no reason to keep CKEditor4 dependency because oe_oembed should support both versions (4 and 5) so I think we should remove that dependency here too.

**Comment by nagyad** [comment]
Fixed.
