### ISSUE TITLE
embed.png not compatible with ckeditor 5

### ISSUE THREAD

**Issue by donquixote** [openeuropa/oe_media#243]
I see this in our status report page:

> The following embed button(s) are not using SVG icons and will not be compatible with CKEditor5
> Media: /web/modules/contrib/oe_media/modules/oe_media_embed/embed.png

This would indicate that the oe_media_embed module is not compatible with CKEditor 5.
We need to replace the png with an svg icon.

**Comment by brummbar** [comment]
The module oe_media_embed is just a legacy, backwards compatible layer [as stated in the readme](https://github.com/openeuropa/oe_media/tree/master/modules/oe_media_embed).
We recommend to move to the new button and disable this module as it's basically empty.
