### ISSUE TITLE
Media AVPortal Source Causes TypeError in MediaAvPortalSourceBase

### ISSUE THREAD

**Issue by tcurelea** [openeuropa/oe_media#251]
The oe_media dependency media_avportal creates a critical error that prevents my website from running correctly and blocks the execution of drush updb.

Details:
I am encountering the following error on my Drupal site (https://github.com/ec-europa/empl-sfc-reference):

TypeError: Drupal\media_avportal\Plugin\media\Source\MediaAvPortalSourceBase::__construct(): Argument #8 ($logger) must be of type Drupal\Core\Logger\LoggerChannelInterface, Psr\Log\NullLogger given, called in /home/ec2-user/environment/sfctest/web/modules/contrib/media_avportal/src/Plugin/media/Source/MediaAvPortalSourceBase.php on line 118 in Drupal\media_avportal\Plugin\media\Source\MediaAvPortalSourceBase->__construct() (line 91 of modules/contrib/media_avportal/src/Plugin/media/Source/MediaAvPortalSourceBase.php).
This error is occurring after updating to oe_media version 1.27 and using Drupal core 10.4-dev.

Steps to Reproduce:
Update to oe_media version 1.27.
Use Drupal core 10.4-dev.
Access the website or run drush updb.
Expected Behavior:
The website should function correctly without throwing a TypeError, and drush updb should execute successfully.

Actual Behavior:
The site crashes with a TypeError, and drush updb fails to execute.

Environment:
oe_media version: 1.27
Drupal core version: 10.4-dev
Additional Information:
The error suggests that Psr\Log\NullLogger is being passed instead of Drupal\Core\Logger\LoggerChannelInterface to the MediaAvPortalSourceBase constructor. This is causing a fatal error during site execution.

Please provide guidance on resolving this issue or confirm if this is a known bug that will be addressed in an upcoming release.

Thank you.

**Comment by brummbar** [comment]
This was caused by a monolog release, as written in https://www.drupal.org/project/media_avportal/issues/3466665#comment-15735884 .
