### ISSUE TITLE
Cannot install oe_media because fields exist already

### ISSUE THREAD

**Issue by dhamaris** [openeuropa/oe_media#252]
Hi, i get this error when trying to install oe_media in my drupal system. 

![image](https://github.com/user-attachments/assets/50e54a62-d0fa-4a95-bc36-8027bd4f8bc8)

Can't you use a naming convention that does not conflict with field names already used by Drupal? Would that be possible?

Thanks

**Comment by brummbar** [comment]
Hi @dhamaris , if there is already configuration with conflicting names, it is left for the developer the exercise to fix the conflicts. It is a fairly simple exercise.
The module installs without issues if you use a clean profile like "minimal" from core.
We cannot rename any bundle as there are dependencies in the other modules or software solutions that use those.
