### ISSUE TITLE
Proposal: GDPR-compliant YouTube Videos

### ISSUE THREAD

**Issue by drupol** [openeuropa/oe_media#37]
I don't know if this module is handling the embedding of Youtube videos, but if this is the case, then this issue should be adressed.

Privacy-enhanced mode allows you to embed YouTube videos without using cookies to track viewing behavior. This means that viewing activity isn't collected to personalize the viewing experience. Instead, video recommendations are contextual and related to the currently played video. Videos playing in a privacy-enhanced mode embedded player won't influence the viewer's browsing experience on YouTube.

Just replaces youtube.com with youtube-nocookie.com in the iframe src and we're done

youtube-nocookie.com has been created and hosted by Google (https://www.whois.com/whois/youtube-nocookie.com).

**Comment by brummbar** [comment]
Cookie handling is done by oe_webtools submodule oe_webtools_cookie_consent.

**Comment by hannolans** [comment]
oe_webtools_cookie_consent is not preventing cookies, it requires the end user to accept cookies to view Youtube videos while the nocookie.com URL version is not tracking users.
